export const login_PageURL="/api/admin/admin-login"
export const update_PasswordURL="/api/admin/forgot-password"

//location


export const statePageUrl="/api/admin/add-state"
export const statelistPageUrl="/api/admin/view-states"
export const districtPageUrl="/api/admin/add-district"
export const districtlistPageUrl="/api/admin/view-all-districts"
export const districtnotTakenUrl="/api/admin/view-nottaken-districts"
export const districtlistinZonalUrl="/api/admin/view-dropdown-districts"
export const nottakenZonalUrl="/api/admin/view-nottaken-zonals"
export const zonalPageUrl="/api/admin/add-zonal"
export const paginatedZonals="/api/admin/view-paginated-zonal"
export const zonallistPageUrl="/api/admin/view-all-zonals"
export const zonallistindropdownUrl="/api/admin/view-dropdown-zonals"
export const panchayathPageUrl="/api/admin/add-panchayath"
export const panchayathlistPageUrl="/api/admin/view-all-panchayaths"
export const panchayathlistindropdownUrl="/api/admin/view-dropdown-panchayaths"
export const paginatedPanchayathUrl="/api/admin/view-paginated-panchayath"
//packages
export const packagesListUrl="/api/admin/view-package"
export const packagesAddUrl="/api/admin/add-package"
export const packagesEditUrl="/api/admin/edit-package"
export const viewpackageListUrl="/api/admin/view-package"
// member
export const memberaddUrl="/api/admin/add-user"
export const viewpendingmemberUrl="/api/admin/view-ready-to-approved-users"
export const approvependingsUrl="/api/admin/accept-user"
export const viewalluserUrl="/api/admin/view-paginated-users"
export const rejectuserUrl ="/api/admin/reject-user"
export const edituserUrl="/api/admin/edit-user-details"
export const viewsingleuserUrl="/api/admin/view-user-profile"
// api for member dashboard
export const uploadimageUrl="/api/admin/upload-home-image"
export const viewuploadsUrl="/api/admin/view-home-images"
export const deleteuploadImageUrl="/api/admin/delete-home-image"
export const uploadvideoUrl="/api/admin/upload-home-video"
export const viewvideouploadUrl="/api/admin/view-home-videos"
export const videodeleteUrl="/api/admin/delete-home-video"
export const editvideouploadUrl="/api/admin/edit-home-video"
export const addAwardUrl="/api/admin/upload-award-details"
export const editAwardUrl="/api/admin/edit-award-details"
export const viewAwardUrl="/api/admin/view-award-details"
export const deleteAwardUrl="/api/admin/delete-award"